import type { Series } from '@/lib/types';

/**
 * 007は25作あるが、大半は一話完結で順番を問われない。
 * 問題になるのは2箇所だけ。
 *   1. ダニエル・クレイグ期の5作（2006〜2021）だけが一続きの物語
 *   2. 『女王陛下の007』(1969) の結末が、半世紀にわたって参照され続ける
 * この2点を押さえれば、残りはどこから観てもよい。
 *
 * 通しの年代順は公開順と変わらないので chronoOrder は同一にしてタブを出さない。
 */
export const bond: Series = {
  slug: 'bond',
  category: 'film',
  name: '007（ジェームズ・ボンド）',
  tagline: '25作あるが、順番が要るのはクレイグ期の5作だけ',
  description:
    '007は60年で25作あり、6人の俳優がボンドを演じてきました。数は多いものの、大半は一話完結で、どこから観ても話は通じます。順番が問題になるのは2箇所だけです。ひとつはダニエル・クレイグ期の5作（2006〜2021年）で、これだけは一続きの物語になっています。もうひとつが『女王陛下の007』（1969年）で、この作品の結末が半世紀にわたって後年の作品に参照され続けます。このページでは、どこを順番どおりに観るべきかを整理しています。',
  films: [
    {
      slug: 'dr-no',
      title: 'ドクター・ノオ',
      originalTitle: 'Dr. No',
      year: 1962,
      note: 'ショーン・コネリー期。第1作。以降20作あまりは、それぞれ独立した事件を描く一話完結の作りが続く',
    },
    {
      slug: 'from-russia',
      title: 'ロシアより愛をこめて',
      originalTitle: 'From Russia with Love',
      year: 1963,
      note: 'ショーン・コネリー期。悪の組織スペクターとの対決。この組織は後年のダニエル・クレイグ期にも再登場する',
    },
    {
      slug: 'goldfinger',
      title: 'ゴールドフィンガー',
      originalTitle: 'Goldfinger',
      year: 1964,
      note: 'ショーン・コネリー期。ボンドカーや秘密兵器といった、以降の定型を決めた1本',
    },
    {
      slug: 'thunderball',
      title: 'サンダーボール作戦',
      originalTitle: 'Thunderball',
      year: 1965,
      note: 'ショーン・コネリー期。1983年の『ネバーセイ・ネバーアゲイン』は、この作品の別バージョンにあたる',
    },
    {
      slug: 'you-only-live-twice',
      title: '007は二度死ぬ',
      originalTitle: 'You Only Live Twice',
      year: 1967,
      note: 'ショーン・コネリー期。日本が舞台。丹波哲郎、若林映子、浜美枝が出演している',
    },
    {
      slug: 'ohmss',
      title: '女王陛下の007',
      originalTitle: "On Her Majesty's Secret Service",
      year: 1969,
      note: 'ジョージ・レーゼンビー期。ボンドが結婚する。この作品の結末は、以降半世紀にわたって何度も参照される',
    },
    {
      slug: 'diamonds',
      title: 'ダイヤモンドは永遠に',
      originalTitle: 'Diamonds Are Forever',
      year: 1971,
      note: 'ショーン・コネリー期。冒頭で『女王陛下の007』の結末を受けた行動を取る。数少ない直接の続きもの',
    },
    {
      slug: 'live-and-let-die',
      title: '死ぬのは奴らだ',
      originalTitle: 'Live and Let Die',
      year: 1973,
      note: 'ロジャー・ムーア期。ムーア期の1作目。作風が軽妙な方向へ移る',
    },
    {
      slug: 'golden-gun',
      title: '黄金銃を持つ男',
      originalTitle: 'The Man with the Golden Gun',
      year: 1974,
      note: 'ロジャー・ムーア期',
    },
    {
      slug: 'spy-who-loved-me',
      title: '私を愛したスパイ',
      originalTitle: 'The Spy Who Loved Me',
      year: 1977,
      note: 'ロジャー・ムーア期。ムーア期の代表作とされることが多い',
    },
    {
      slug: 'moonraker',
      title: 'ムーンレイカー',
      originalTitle: 'Moonraker',
      year: 1979,
      note: 'ロジャー・ムーア期。宇宙が舞台。シリーズで最も現実離れした1本',
    },
    {
      slug: 'for-your-eyes-only',
      title: 'ユア・アイズ・オンリー',
      originalTitle: 'For Your Eyes Only',
      year: 1981,
      note: 'ロジャー・ムーア期。冒頭にボンドが亡き妻の墓を訪ねる場面がある。『女王陛下の007』を観ていると意味が分かる',
    },
    {
      slug: 'octopussy',
      title: 'オクトパシー',
      originalTitle: 'Octopussy',
      year: 1983,
      note: 'ロジャー・ムーア期',
    },
    {
      slug: 'view-to-a-kill',
      title: '美しき獲物たち',
      originalTitle: 'A View to a Kill',
      year: 1985,
      note: 'ロジャー・ムーア期。ムーア期の最終作',
    },
    {
      slug: 'living-daylights',
      title: 'リビング・デイライツ',
      originalTitle: 'The Living Daylights',
      year: 1987,
      note: 'ティモシー・ダルトン期。ダルトン期の1作目。原作寄りの硬い作風に振れる',
    },
    {
      slug: 'licence-to-kill',
      title: '消されたライセンス',
      originalTitle: 'Licence to Kill',
      year: 1989,
      note: 'ティモシー・ダルトン期。ダルトン期は2作で終わり、次作まで6年空いた',
    },
    {
      slug: 'goldeneye',
      title: 'ゴールデンアイ',
      originalTitle: 'GoldenEye',
      year: 1995,
      note: 'ピアース・ブロスナン期。冷戦終結後のボンド。Mを女性が演じるようになる',
    },
    {
      slug: 'tomorrow-never-dies',
      title: 'トゥモロー・ネバー・ダイ',
      originalTitle: 'Tomorrow Never Dies',
      year: 1997,
      note: 'ピアース・ブロスナン期。ミシェル・ヨーが共演',
    },
    {
      slug: 'world-is-not-enough',
      title: 'ワールド・イズ・ノット・イナフ',
      originalTitle: 'The World Is Not Enough',
      year: 1999,
      note: 'ピアース・ブロスナン期',
    },
    {
      slug: 'die-another-day',
      title: 'ダイ・アナザー・デイ',
      originalTitle: 'Die Another Day',
      year: 2002,
      note: 'ピアース・ブロスナン期。シリーズ40周年作。この次でシリーズは仕切り直される',
    },
    {
      slug: 'casino-royale',
      title: 'カジノ・ロワイヤル',
      originalTitle: 'Casino Royale',
      year: 2006,
      note: 'ダニエル・クレイグ期。ボンドが00の資格を得たばかりという設定に戻して仕切り直した。ここから5作が一続きの物語になる',
    },
    {
      slug: 'quantum',
      title: '慰めの報酬',
      originalTitle: 'Quantum of Solace',
      year: 2008,
      note: 'ダニエル・クレイグ期。『カジノ・ロワイヤル』の直後から始まる。シリーズで唯一、前作の直接の続きとして作られた',
    },
    {
      slug: 'skyfall',
      title: 'スカイフォール',
      originalTitle: 'Skyfall',
      year: 2012,
      note: 'ダニエル・クレイグ期。シリーズ50周年作。ボンドの生い立ちが描かれる',
    },
    {
      slug: 'spectre',
      title: 'スペクター',
      originalTitle: 'Spectre',
      year: 2015,
      note: 'ダニエル・クレイグ期。クレイグ期のそれまでの4作を1本の線に繋ぎ直す',
    },
    {
      slug: 'no-time-to-die',
      title: '007／ノー・タイム・トゥ・ダイ',
      originalTitle: 'No Time to Die',
      year: 2021,
      note: 'ダニエル・クレイグ期。クレイグ期の完結編。『女王陛下の007』の主題歌が使われるなど、過去作への参照が多い',
    },
  ],
  releaseOrder: [
    'dr-no',
    'from-russia',
    'goldfinger',
    'thunderball',
    'you-only-live-twice',
    'ohmss',
    'diamonds',
    'live-and-let-die',
    'golden-gun',
    'spy-who-loved-me',
    'moonraker',
    'for-your-eyes-only',
    'octopussy',
    'view-to-a-kill',
    'living-daylights',
    'licence-to-kill',
    'goldeneye',
    'tomorrow-never-dies',
    'world-is-not-enough',
    'die-another-day',
    'casino-royale',
    'quantum',
    'skyfall',
    'spectre',
    'no-time-to-die',
  ],
  // 一話完結が大半で、作中の年代は公開時期にほぼ沿う。
  // 公開順と同じにしてタブを出さない
  chronoOrder: [
    'dr-no',
    'from-russia',
    'goldfinger',
    'thunderball',
    'you-only-live-twice',
    'ohmss',
    'diamonds',
    'live-and-let-die',
    'golden-gun',
    'spy-who-loved-me',
    'moonraker',
    'for-your-eyes-only',
    'octopussy',
    'view-to-a-kill',
    'living-daylights',
    'licence-to-kill',
    'goldeneye',
    'tomorrow-never-dies',
    'world-is-not-enough',
    'die-another-day',
    'casino-royale',
    'quantum',
    'skyfall',
    'spectre',
    'no-time-to-die',
  ],
  recommendedLabel: 'いまから入るならこの5本',
  recommendedDescription:
    'ダニエル・クレイグ期の5作です。25作の中でここだけが一続きの物語で、順番どおりに観る必要があります。逆にいえば、この5本を観るのに過去20作の予習は要りません。ボンドが00の資格を得たばかりという設定から始まるので、シリーズを知らない人が入るのに最も向いています。',
  recommendedOrder: [
    {
      slug: 'casino-royale',
      reason: 'ボンドが00の資格を得たばかりという設定に戻して仕切り直した1作目。過去20作の予習は要らない',
    },
    { slug: 'quantum', reason: '前作の直後から始まる。シリーズで唯一、直接の続編として作られた' },
    { slug: 'skyfall' },
    { slug: 'spectre', reason: 'それまでの4作を1本の線に繋ぎ直す' },
    { slug: 'no-time-to-die', reason: '完結編。ここまで順番どおりに観ていることが前提になっている' },
  ],
  caveats: [
    '007は25作ありますが、大半は一話完結です。前作を観ていなくても話は通じるように作られているため、25作を順番に追う必要はありません。',
    '例外がダニエル・クレイグ期の5作（『カジノ・ロワイヤル』『慰めの報酬』『スカイフォール』『スペクター』『ノー・タイム・トゥ・ダイ』）です。この5本だけは一続きの物語で、順番どおりに観る必要があります。いまから入るなら、ここだけで足ります。',
    'もうひとつの例外が『女王陛下の007』（1969年）です。ボンドが結婚するこの作品の結末は、『ダイヤモンドは永遠に』の冒頭、『ユア・アイズ・オンリー』の墓参りの場面、そして『ノー・タイム・トゥ・ダイ』の主題歌にいたるまで、半世紀にわたって参照され続けます。俳優が1作だけ交代した回でもあり、初見で飛ばされやすい作品ですが、後年の作品の受け取り方が変わります。',
    'ボンド役は6人が演じてきました。ショーン・コネリー（6作）、ジョージ・レーゼンビー（1作）、ロジャー・ムーア（7作）、ティモシー・ダルトン（2作）、ピアース・ブロスナン（4作）、ダニエル・クレイグ（5作）です。俳優が替わっても『カジノ・ロワイヤル』までは同じ世界の続きとして扱われていました。',
    '『007／カジノ・ロワイヤル』（1967年）と『ネバーセイ・ネバーアゲイン』（1983年）は、権利関係の事情で本編とは別に作られた作品です。1967年版はコメディ、1983年版は『サンダーボール作戦』の別バージョンにあたります。どちらも本編には数えられていません。',
    '2021年の『ノー・タイム・トゥ・ダイ』でクレイグ期は完結しました。次作はドゥニ・ビルヌーブ監督、Amazon MGMスタジオ製作で進行していますが、2026年9月時点でボンド役は決まっていません。2027年に撮影開始、2028年公開を目指すと報じられています。',
    '『007は二度死ぬ』（1967年）は日本が舞台で、丹波哲郎・若林映子・浜美枝が出演しています。姫路城や神戸港が登場します。',
  ],
  sources: [
    {
      label: '次期ジェームズ・ボンドの選考状況（映画.com・2026年6月）',
      url: 'https://eiga.com/news/20260625/16/',
    },
    {
      label: '新ボンドは無名の若手英国俳優、2028年公開目指す（シネマトゥデイ）',
      url: 'https://www.cinematoday.jp/news/N0151013',
    },
  ],
};
