import type { Series } from '@/lib/types';

/**
 * ゴジラは1本の続き物ではない。1954年の第1作を出発点に、時代ごとに
 * 何度も作り直されている。
 *   昭和シリーズ      1954〜1975（15作）… 2作目以降は後の系統から切り離された
 *   平成VSシリーズ    1984〜1995（7作） … 1954年の直接の続編として作り直し
 *   ミレニアムシリーズ 1999〜2004（6作） … 6作それぞれが1954年から独立して分岐
 *   シン・ゴジラ以降   2016〜          … それぞれ独立。-1.0 と -0.0 だけが続きもの
 *   ハリウッド版      1998 / 2014〜     … 1998年版は独立、2014年以降が一続き
 *
 * つまり通しの時系列は存在しない。chronoOrder は公開順と同じにしてタブを出さず、
 * 3つ目の順番を「初めて観る人の順」に充てている。
 * 40作を前にした人が本当に知りたいのは「どれを観なくていいか」だからだ。
 */
export const godzilla: Series = {
  slug: 'godzilla',
  name: 'ゴジラ',
  category: 'film',
  tagline: '70年で40本以上。何度も作り直されていて、全部は繋がらない',
  description:
    'ゴジラの映画は40作以上ありますが、1本の続き物ではありません。1954年の第1作を出発点として、昭和・平成VS・ミレニアム・シン・ゴジラ以降という具合に、時代ごとに何度も作り直されています。さらにハリウッド版が2系統あります。系統をまたいで観る必要はなく、どこから入っても話は通じるように作られています。このページでは、どの作品とどの作品が繋がっているのかを系統ごとに整理しています。',
  films: [
    // ── 昭和シリーズ 1954〜1975（全15作） ──
    {
      slug: 'gojira-1954',
      title: 'ゴジラ',
      originalTitle: 'ゴジラ',
      year: 1954,
      note: '第1作。ほぼすべてのシリーズが、この1本を出発点にして枝分かれしていく。以降どの系統に進むにしても、観ておく価値があるのはここ',
    },
    {
      slug: 'gyakushu',
      title: 'ゴジラの逆襲',
      originalTitle: 'ゴジラの逆襲',
      year: 1955,
      note: '昭和シリーズの2作目。平成VSシリーズはこの作品以降を「なかったこと」にして作られている',
    },
    {
      slug: 'king-kong-tai',
      title: 'キングコング対ゴジラ',
      originalTitle: 'キングコング対ゴジラ',
      year: 1962,
      note: 'シリーズ最大のヒット作。コングとの対決は2021年のハリウッド版まで再現されなかった',
    },
    {
      slug: 'mothra-tai',
      title: 'モスラ対ゴジラ',
      originalTitle: 'モスラ対ゴジラ',
      year: 1964,
      note: 'モスラの初参戦。この頃からゴジラは怪獣同士の対決ものへ移っていく',
    },
    {
      slug: 'san-daikaiju',
      title: '三大怪獣 地球最大の決戦',
      originalTitle: '三大怪獣 地球最大の決戦',
      year: 1964,
      note: 'キングギドラの初登場。ゴジラが人類の側につく転換点にあたる',
    },
    {
      slug: 'kaiju-daisenso',
      title: '怪獣大戦争',
      originalTitle: '怪獣大戦争',
      year: 1965,
      note: 'X星人が登場する宇宙もの。以降しばらく子供向けの色が強まる',
    },
    {
      slug: 'ebirah',
      title: 'ゴジラ・エビラ・モスラ 南海の大決闘',
      originalTitle: 'ゴジラ・エビラ・モスラ 南海の大決闘',
      year: 1966,
      note: 'もとはキングコング主演として企画された作品。南海を舞台にした異色作',
    },
    {
      slug: 'son-of-godzilla',
      title: '怪獣島の決戦 ゴジラの息子',
      originalTitle: '怪獣島の決戦 ゴジラの息子',
      year: 1967,
      note: 'ミニラが初登場。親子ものの色が濃い',
    },
    {
      slug: 'soshingeki',
      title: '怪獣総進撃',
      originalTitle: '怪獣総進撃',
      year: 1968,
      note: '当初はシリーズの完結編として作られた。11体の怪獣が集結する',
    },
    {
      slug: 'all-monsters-attack',
      title: 'ゴジラ・ミニラ・ガバラ オール怪獣大進撃',
      originalTitle: 'ゴジラ・ミニラ・ガバラ オール怪獣大進撃',
      year: 1969,
      note: '少年の空想として怪獣が登場する。過去作の映像を多く使っており、独立した1本とは言いにくい',
    },
    {
      slug: 'hedorah',
      title: 'ゴジラ対ヘドラ',
      originalTitle: 'ゴジラ対ヘドラ',
      year: 1971,
      note: '公害をテーマにした異色作。作風がシリーズの中で際立って違う',
    },
    {
      slug: 'gigan',
      title: '地球攻撃命令 ゴジラ対ガイガン',
      originalTitle: '地球攻撃命令 ゴジラ対ガイガン',
      year: 1972,
      note: 'ガイガンの初登場',
    },
    {
      slug: 'megalo',
      title: 'ゴジラ対メガロ',
      originalTitle: 'ゴジラ対メガロ',
      year: 1973,
      note: 'ジェットジャガーが登場。予算縮小が進んだ時期の作品',
    },
    {
      slug: 'tai-mechagodzilla',
      title: 'ゴジラ対メカゴジラ',
      originalTitle: 'ゴジラ対メカゴジラ',
      year: 1974,
      note: 'メカゴジラの初登場。1993年版・2002年版とは設定が繋がらない',
    },
    {
      slug: 'mechagodzilla-gyakushu',
      title: 'メカゴジラの逆襲',
      originalTitle: 'メカゴジラの逆襲',
      year: 1975,
      note: '昭和シリーズの最終作。この後、9年間ゴジラ映画は作られなかった',
    },
    // ── 平成VSシリーズ 1984〜1995（全7作） ──
    {
      slug: 'gojira-1984',
      title: 'ゴジラ',
      originalTitle: 'ゴジラ',
      year: 1984,
      note: '平成VSシリーズの開幕作。1954年の第1作の直接の続編として作られており、その間の昭和14作は起きなかったことになっている',
    },
    {
      slug: 'biollante',
      title: 'ゴジラvsビオランテ',
      originalTitle: 'ゴジラvsビオランテ',
      year: 1989,
      note: '『ゴジラ』(1984) の直接の続き。ここから7作が一続きの物語になる',
    },
    {
      slug: 'king-ghidorah',
      title: 'ゴジラvsキングギドラ',
      originalTitle: 'ゴジラvsキングギドラ',
      year: 1991,
      note: '時間移動を扱い、ゴジラの誕生の経緯そのものを書き換える。平成VSの中でも要になる1本',
    },
    {
      slug: 'vs-mothra',
      title: 'ゴジラvsモスラ',
      originalTitle: 'ゴジラvsモスラ',
      year: 1992,
      note: 'シリーズ最大の観客動員を記録した',
    },
    {
      slug: 'vs-mechagodzilla',
      title: 'ゴジラvsメカゴジラ',
      originalTitle: 'ゴジラvsメカゴジラ',
      year: 1993,
      note: '1974年版・2002年版のメカゴジラとは別物。名前が同じだけで繋がらない',
    },
    {
      slug: 'space-godzilla',
      title: 'ゴジラvsスペースゴジラ',
      originalTitle: 'ゴジラvsスペースゴジラ',
      year: 1994,
      note: '『ビオランテ』『vsモスラ』の登場人物が再登場する',
    },
    {
      slug: 'destoroyah',
      title: 'ゴジラvsデストロイア',
      originalTitle: 'ゴジラvsデストロイア',
      year: 1995,
      note: '平成VSシリーズの完結編。1954年の第1作で使われたオキシジェン・デストロイヤーが再び物語の中心に来るため、第1作を観ているかどうかで受け取り方が大きく変わる',
    },
    // ── ミレニアムシリーズ 1999〜2004（全6作） ──
    {
      slug: 'godzilla-2000',
      title: 'ゴジラ2000 ミレニアム',
      originalTitle: 'ゴジラ2000 ミレニアム',
      year: 1999,
      note: 'ミレニアムシリーズの1作目。1954年の第1作だけを前提にして作り直されている',
    },
    {
      slug: 'megaguirus',
      title: 'ゴジラ×メガギラス G消滅作戦',
      originalTitle: 'ゴジラ×メガギラス G消滅作戦',
      year: 2000,
      note: '前作とは繋がらない。1954年から独立して枝分かれした別の世界',
    },
    {
      slug: 'gmk',
      title: 'ゴジラ・モスラ・キングギドラ 大怪獣総攻撃',
      originalTitle: 'ゴジラ・モスラ・キングギドラ 大怪獣総攻撃',
      year: 2001,
      note: 'ゴジラを戦没者の怨念とする異色作。作中に1998年のハリウッド版を否定する台詞があり、他のどの作品とも繋がらない',
    },
    {
      slug: 'kiryu',
      title: 'ゴジラ×メカゴジラ',
      originalTitle: 'ゴジラ×メカゴジラ',
      year: 2002,
      note: '1954年に倒されたゴジラの骨からメカゴジラを作るという設定。次作『東京SOS』と2本で1つの物語になる',
    },
    {
      slug: 'tokyo-sos',
      title: 'ゴジラ×モスラ×メカゴジラ 東京SOS',
      originalTitle: 'ゴジラ×モスラ×メカゴジラ 東京SOS',
      year: 2003,
      note: '『ゴジラ×メカゴジラ』(2002) の直接の続編。ミレニアムシリーズの中で唯一の続きもの',
    },
    {
      slug: 'final-wars',
      title: 'ゴジラ FINAL WARS',
      originalTitle: 'ゴジラ FINAL WARS',
      year: 2004,
      note: 'シリーズ50周年記念作。過去作の怪獣が多数登場するが、設定は独立している',
    },
    // ── シン・ゴジラ以降と、アニメ3部作 ──
    {
      slug: 'shin-godzilla',
      title: 'シン・ゴジラ',
      originalTitle: 'シン・ゴジラ',
      year: 2016,
      note: '庵野秀明・樋口真嗣による全面的な作り直し。他のどの作品とも繋がらず、前提知識も要らない',
    },
    {
      slug: 'anime-1',
      title: 'GODZILLA 怪獣惑星',
      originalTitle: 'GODZILLA 怪獣惑星',
      year: 2017,
      note: 'アニメ3部作の1作目。人類が地球を捨てて2万年後に帰還する設定で、実写シリーズとは無関係',
    },
    {
      slug: 'anime-2',
      title: 'GODZILLA 決戦機動増殖都市',
      originalTitle: 'GODZILLA 決戦機動増殖都市',
      year: 2018,
      note: 'アニメ3部作の2作目。1作目からの直接の続き',
    },
    {
      slug: 'anime-3',
      title: 'GODZILLA 星を喰う者',
      originalTitle: 'GODZILLA 星を喰う者',
      year: 2018,
      note: 'アニメ3部作の完結編',
    },
    {
      slug: 'minus-one',
      title: 'ゴジラ-1.0',
      originalTitle: 'ゴジラ-1.0',
      year: 2023,
      note: '1954年の第1作より前、終戦直後の日本を舞台にする。米アカデミー賞視覚効果賞を受賞した',
    },
    {
      slug: 'minus-zero',
      title: 'ゴジラ-0.0',
      originalTitle: 'ゴジラ-0.0',
      year: 2026,
      note: '2026年11月3日公開。『ゴジラ-1.0』の直接の続編で、前作の死闘から2年後を描く。山崎貴監督、神木隆之介・浜辺美波が続投し、長澤まさみが新たに加わる',
    },
    // ── ハリウッド版 ──
    {
      slug: 'tristar-1998',
      title: 'GODZILLA',
      originalTitle: 'Godzilla',
      year: 1998,
      note: 'ローランド・エメリッヒ監督によるハリウッド版。2014年以降のシリーズとは繋がらない独立作で、東宝側もこの作品のゴジラを別の怪獣として扱っている',
    },
    {
      slug: 'legendary-2014',
      title: 'GODZILLA ゴジラ',
      originalTitle: 'Godzilla',
      year: 2014,
      note: 'モンスターバースの出発点。ここから6作が一続きになる',
    },
    {
      slug: 'skull-island',
      title: 'キングコング：髑髏島の巨神',
      originalTitle: 'Kong: Skull Island',
      year: 2017,
      note: 'ゴジラは登場しないが、モンスターバースの2作目。コングの背景がここで語られるため、飛ばすと『ゴジラvsコング』の前提が抜ける',
    },
    {
      slug: 'kotm',
      title: 'ゴジラ キング・オブ・モンスターズ',
      originalTitle: 'Godzilla: King of the Monsters',
      year: 2019,
      note: 'モスラ・キングギドラ・ラドンがハリウッド版に登場する',
    },
    {
      slug: 'gvk',
      title: 'ゴジラvsコング',
      originalTitle: 'Godzilla vs. Kong',
      year: 2021,
      note: '1962年の『キングコング対ゴジラ』以来の対決',
    },
    {
      slug: 'new-empire',
      title: 'ゴジラxコング 新たなる帝国',
      originalTitle: 'Godzilla x Kong: The New Empire',
      year: 2024,
      note: '『ゴジラvsコング』の直接の続編',
    },
    {
      slug: 'supernova',
      title: 'ゴジラxコング スーパーノヴァ',
      originalTitle: 'Godzilla x Kong: Supernova',
      year: 2027,
      note: '2027年3月26日全米公開予定。モンスターバースの6作目',
    },
  ],
  releaseOrder: [
    'gojira-1954',
    'gyakushu',
    'king-kong-tai',
    'mothra-tai',
    'san-daikaiju',
    'kaiju-daisenso',
    'ebirah',
    'son-of-godzilla',
    'soshingeki',
    'all-monsters-attack',
    'hedorah',
    'gigan',
    'megalo',
    'tai-mechagodzilla',
    'mechagodzilla-gyakushu',
    'gojira-1984',
    'biollante',
    'king-ghidorah',
    'vs-mothra',
    'vs-mechagodzilla',
    'space-godzilla',
    'destoroyah',
    'tristar-1998',
    'godzilla-2000',
    'megaguirus',
    'gmk',
    'kiryu',
    'tokyo-sos',
    'final-wars',
    'legendary-2014',
    'shin-godzilla',
    'anime-1',
    'skull-island',
    'anime-2',
    'anime-3',
    'kotm',
    'gvk',
    'minus-one',
    'new-empire',
    'minus-zero',
    'supernova',
  ],
  // 系統ごとに世界が分かれており、通しの年代順は存在しない。
  // 公開順と同じにしてタブを出さない
  chronoOrder: [
    'gojira-1954',
    'gyakushu',
    'king-kong-tai',
    'mothra-tai',
    'san-daikaiju',
    'kaiju-daisenso',
    'ebirah',
    'son-of-godzilla',
    'soshingeki',
    'all-monsters-attack',
    'hedorah',
    'gigan',
    'megalo',
    'tai-mechagodzilla',
    'mechagodzilla-gyakushu',
    'gojira-1984',
    'biollante',
    'king-ghidorah',
    'vs-mothra',
    'vs-mechagodzilla',
    'space-godzilla',
    'destoroyah',
    'tristar-1998',
    'godzilla-2000',
    'megaguirus',
    'gmk',
    'kiryu',
    'tokyo-sos',
    'final-wars',
    'legendary-2014',
    'shin-godzilla',
    'anime-1',
    'skull-island',
    'anime-2',
    'anime-3',
    'kotm',
    'gvk',
    'minus-one',
    'new-empire',
    'minus-zero',
    'supernova',
  ],
  recommendedLabel: '初めて観る人の順',
  recommendedDescription:
    '40作すべてを追う必要はありません。1954年の第1作を観たうえで、興味のある系統をひとつ選べば足ります。ここでは前提知識が要らず、単体で完結している作品を並べています。',
  recommendedOrder: [
    {
      slug: 'gojira-1954',
      reason: 'すべての系統がここから枝分かれする。以降どこへ進んでも前提になる唯一の1本',
    },
    {
      slug: 'minus-one',
      reason: '1954年の第1作より前の時代を描く。予習が要らず、単体で完結している',
    },
    {
      slug: 'minus-zero',
      reason: '『ゴジラ-1.0』の2年後。この2本だけが直接つながっている',
    },
    {
      slug: 'shin-godzilla',
      reason: '他のどの作品とも繋がらない独立作。現代の日本を舞台にしている',
    },
    {
      slug: 'legendary-2014',
      reason: 'ここからハリウッド版の一続きのシリーズが始まる',
    },
    { slug: 'skull-island', reason: 'ゴジラは出ないが、コングの背景がここで語られる' },
    { slug: 'kotm' },
    { slug: 'gvk' },
    { slug: 'new-empire' },
    { slug: 'supernova', reason: '2027年3月全米公開予定' },
  ],
  caveats: [
    'ゴジラの映画は1本の続き物ではありません。1954年の第1作を出発点に、時代ごとに何度も作り直されています。昭和・平成VS・ミレニアム・シン・ゴジラ以降・ハリウッド版という系統があり、系統をまたいで観る必要はありません。通しの時系列も存在しないため、このページでは年代順のタブを出していません。',
    'まず観るなら1954年の第1作です。ほぼすべての系統がこの1本を前提にしており、逆にいえば、この1本さえ観ていれば大半の作品に入れます。',
    '『ゴジラ-0.0』（2026年11月3日公開）を観るための予習は、『ゴジラ-1.0』（2023年）1本だけです。前作の死闘から2年後を描く直接の続編で、それ以外の作品は関係しません。40作を遡る必要はありません。',
    '平成VSシリーズ（1984〜1995年の7作）は、1954年の第1作の直接の続編として作られています。昭和シリーズの2作目以降にあたる14作は、起きなかったことになっています。つまり『ゴジラ』（1984年）の前に観ておくべきなのは、1954年の1作だけです。',
    'ミレニアムシリーズ（1999〜2004年の6作）は、6作それぞれが1954年の第1作から独立して枝分かれします。互いに繋がりません。例外は『ゴジラ×メカゴジラ』（2002年）と『ゴジラ×モスラ×メカゴジラ 東京SOS』（2003年）で、この2本だけが続きものです。',
    'メカゴジラは1974年・1993年・2002年に登場しますが、いずれも別のシリーズの別の機体です。名前が同じだけで、設定は繋がりません。',
    'ハリウッド版は2系統あります。1998年のローランド・エメリッヒ版は独立した作品で、以降のシリーズとは繋がりません。2014年の『GODZILLA ゴジラ』から始まる6作（モンスターバース）が、一続きになっているほうです。',
    '『キングコング：髑髏島の巨神』（2017年）にはゴジラが登場しませんが、モンスターバースの2作目です。コングの出自がここで語られるため、飛ばすと『ゴジラvsコング』以降が分かりにくくなります。',
    'アニメ3部作（『怪獣惑星』『決戦機動増殖都市』『星を喰う者』）は、人類が地球を捨てて2万年後に帰還するという設定で、実写のどのシリーズとも繋がりません。3本続けて観る必要はありますが、他は不要です。',
    '『ゴジラ-1.0/C』は『ゴジラ-1.0』をモノクロにした版で、中身は同じ映画です。どちらか一方を観れば足ります。',
    'ドラマ『モナーク：レガシー・オブ・モンスターズ』（Apple TV+、シーズン2は2026年2月配信）はモンスターバースの一部で、2014年版と直接つながります。ただし映画だけを追う場合、観ていなくても支障はありません。TVアニメ『ゴジラ シンギュラポイント』（2021年）は、これとは別の独立した作品です。',
  ],
  sources: [
    { label: 'ゴジラ公式サイト（東宝）', url: 'https://godzilla.store/gojira/' },
    {
      label: 'ゴジラシリーズ - Wikipedia（全作品一覧）',
      url: 'https://ja.wikipedia.org/wiki/%E3%82%B4%E3%82%B8%E3%83%A9%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA',
    },
    {
      label: '『ゴジラ-0.0』最新予告と公開日（映画.com）',
      url: 'https://eiga.com/news/20260908/37/',
    },
    {
      label: '『ゴジラ×コング：スーパーノヴァ』2027年3月全米公開（THR Japan）',
      url: 'https://hollywoodreporter.jp/movies/109688/',
    },
  ],
};
