import type { Series } from '@/lib/types';

/**
 * ガンダムは「シリーズ全部」を一本の順番に並べられない。
 * SEED や 00、鉄血、水星の魔女は、宇宙世紀とは無関係の独立した世界だからだ。
 * ここで扱うのは、順番が実際に問題になる宇宙世紀（U.C.）だけに絞っている。
 *
 * 宇宙世紀は公開順と年代順が大きく食い違う。
 * 外伝OVA（0080・0083・08小隊）はどれも一年戦争前後の話なのに、
 * 制作されたのは Z・ZZ・逆襲のシャアより後だからだ。
 */
export const gundam: Series = {
  slug: 'gundam',
  name: 'ガンダム（宇宙世紀）',
  tagline: '公開順と年代順が最も食い違うシリーズ。どこから入るか',
  description:
    'ガンダムには複数の独立した世界があり、それぞれ繋がっていません。順番が問題になるのは、1979年の『機動戦士ガンダム』から続く宇宙世紀（U.C.）だけです。宇宙世紀は本編の後に外伝OVAが何本も作られたため、公開順と作中の年代順が大きくずれます。SEED・00・鉄血のオルフェンズ・水星の魔女などは別世界なので、宇宙世紀を観ていなくても単独で楽しめます。',
  films: [
    // THE ORIGIN は TMDb 側で全6章が個別の作品として登録されているので、
    // こちらも1本ずつ持つ。章ごとにポスターと尺が違い、進捗も章単位で追える。
    // ID は検索で引けないため直接指定する（scripts/tmdb-find.mjs で調べた）。
    {
      slug: 'origin-1',
      title: '機動戦士ガンダム THE ORIGIN I 青い瞳のキャスバル',
      originalTitle: '機動戦士ガンダム THE ORIGIN I 青い瞳のキャスバル',
      year: 2015,
      tmdbId: 329365,
      setting: 'U.C.0068',
      note: 'シャアとセイラの少年期を描く前日譚。全6章で一年戦争の開戦前夜までをたどる。1stガンダムの登場人物を知っている前提で作られているため、最初に観ると人物関係が分かりにくい',
    },
    {
      slug: 'origin-2',
      title: '機動戦士ガンダム THE ORIGIN II 哀しみのアルテイシア',
      originalTitle: '機動戦士ガンダム THE ORIGIN II 哀しみのアルテイシア',
      year: 2015,
      tmdbId: 368708,
    },
    {
      slug: 'origin-3',
      title: '機動戦士ガンダム THE ORIGIN III 暁の蜂起',
      originalTitle: '機動戦士ガンダム THE ORIGIN III 暁の蜂起',
      year: 2016,
      tmdbId: 397366,
    },
    {
      slug: 'origin-4',
      title: '機動戦士ガンダム THE ORIGIN IV 運命の前夜',
      originalTitle: '機動戦士ガンダム THE ORIGIN IV 運命の前夜',
      year: 2016,
      tmdbId: 403850,
    },
    {
      slug: 'origin-5',
      title: '機動戦士ガンダム THE ORIGIN V 激突 ルウム会戦',
      originalTitle: '機動戦士ガンダム THE ORIGIN V 激突 ルウム会戦',
      year: 2017,
      tmdbId: 428862,
      setting: 'U.C.0079',
      note: 'ルウム戦役。一年戦争の緒戦にあたる',
    },
    {
      slug: 'origin-6',
      title: '機動戦士ガンダム THE ORIGIN VI 誕生 赤い彗星',
      originalTitle: '機動戦士ガンダム THE ORIGIN VI 誕生 赤い彗星',
      year: 2018,
      tmdbId: 475935,
      setting: 'U.C.0079',
      note: '全6章の完結編。ここから1stガンダム本編の時期に入る',
    },
    {
      slug: 'tv-1979',
      title: '機動戦士ガンダム（TVアニメ）',
      originalTitle: '機動戦士ガンダム',
      year: 1979,
      kind: 'tv',
      episodes: 43,
      setting: 'U.C.0079',
      note: 'すべての出発点。放送当時は打ち切りで、予定より短い43話で終わっている',
    },
    {
      slug: 'movie-1',
      title: '劇場版 機動戦士ガンダム',
      originalTitle: '機動戦士ガンダム',
      year: 1981,
      setting: 'U.C.0079',
      note: 'TV版43話を3本にまとめ直した劇場版の1作目。TV版とは別の入口で、両方観る必要はない',
    },
    {
      slug: 'movie-2',
      title: '劇場版 機動戦士ガンダムII 哀・戦士編',
      originalTitle: '機動戦士ガンダムII 哀・戦士編',
      year: 1981,
      setting: 'U.C.0079',
    },
    {
      slug: 'movie-3',
      title: '劇場版 機動戦士ガンダムIII めぐりあい宇宙編',
      originalTitle: '機動戦士ガンダムIII めぐりあい宇宙編',
      year: 1982,
      setting: 'U.C.0079',
      note: '終盤は新作カットに差し替えられており、TV版とは結末の描写が異なる',
    },
    {
      slug: '08th-ms-team',
      title: '機動戦士ガンダム 第08MS小隊',
      originalTitle: '機動戦士ガンダム 第08MS小隊',
      year: 1996,
      kind: 'tv',
      episodes: 12,
      setting: 'U.C.0079',
      note: '一年戦争の地上戦を描いた外伝。本編の登場人物はほとんど出てこないので、単独で観られる',
    },
    {
      slug: '0080',
      title: '機動戦士ガンダム0080 ポケットの中の戦争',
      originalTitle: '機動戦士ガンダム0080 ポケットの中の戦争',
      year: 1989,
      kind: 'tv',
      episodes: 6,
      setting: 'U.C.0079〜0080',
      note: '少年の視点から戦争を描く6話完結の外伝。全6話と短く、宇宙世紀の入口として薦められることが多い',
    },
    {
      slug: '0083',
      title: '機動戦士ガンダム0083 STARDUST MEMORY',
      originalTitle: '機動戦士ガンダム0083 STARDUST MEMORY',
      year: 1991,
      kind: 'tv',
      episodes: 13,
      setting: 'U.C.0083',
      note: '一年戦争と『Zガンダム』の間を埋める話。ラストがZの前提に直接つながる',
    },
    {
      slug: 'zeta',
      title: '機動戦士Zガンダム',
      originalTitle: '機動戦士Zガンダム',
      year: 1985,
      kind: 'tv',
      episodes: 50,
      setting: 'U.C.0087',
      note: '1stの7年後。主人公は交代するが、シャアやブライトなど前作の人物が引き続き登場する',
    },
    {
      slug: 'zz',
      title: '機動戦士ガンダムZZ',
      originalTitle: '機動戦士ガンダムZZ',
      year: 1986,
      kind: 'tv',
      episodes: 47,
      setting: 'U.C.0088',
      note: 'Zの直接の続き。序盤は明るい作風で、Zとの落差に戸惑う人が多い。後半は再びシリアスに戻る',
    },
    {
      slug: 'char-counterattack',
      title: '機動戦士ガンダム 逆襲のシャア',
      originalTitle: '機動戦士ガンダム 逆襲のシャア',
      year: 1988,
      setting: 'U.C.0093',
      note: 'アムロとシャアの決着。1stとZを観ていることを前提に作られている',
    },
    {
      slug: 'unicorn',
      title: '機動戦士ガンダムUC（ユニコーン）',
      originalTitle: '機動戦士ガンダムUC',
      year: 2010,
      kind: 'tv',
      episodes: 7,
      setting: 'U.C.0096',
      note: '逆襲のシャアの3年後。1st・Z・ZZ・逆シャアの積み重ねを回収する作りで、予備知識があるほど効く',
    },
    {
      slug: 'narrative',
      title: '機動戦士ガンダムNT（ナラティブ）',
      originalTitle: '機動戦士ガンダムNT',
      year: 2018,
      setting: 'U.C.0097',
      note: 'ユニコーンの直接の続編。ユニコーンを観ていないと話が分からない',
    },
    {
      slug: 'hathaway',
      title: '機動戦士ガンダム 閃光のハサウェイ',
      originalTitle: '機動戦士ガンダム 閃光のハサウェイ',
      year: 2021,
      setting: 'U.C.0105',
      note: '逆襲のシャアの12年後。主人公は逆シャアに登場した少年ハサウェイの成長後',
    },
    {
      slug: 'hathaway-2',
      title: '機動戦士ガンダム 閃光のハサウェイ キルケーの魔女',
      originalTitle: '機動戦士ガンダム 閃光のハサウェイ キルケーの魔女',
      year: 2026,
      setting: 'U.C.0105',
      note: '閃光のハサウェイ第2部。2026年1月30日公開。3部作の予定で、完結編は未公開',
    },
  ],
  releaseOrder: [
    'tv-1979',
    'movie-1',
    'movie-2',
    'movie-3',
    'zeta',
    'zz',
    'char-counterattack',
    '0080',
    '0083',
    '08th-ms-team',
    'unicorn',
    'origin-1',
    'origin-2',
    'origin-3',
    'origin-4',
    'origin-5',
    'origin-6',
    'narrative',
    'hathaway',
    'hathaway-2',
  ],
  chronoOrder: [
    'origin-1',
    'origin-2',
    'origin-3',
    'origin-4',
    'origin-5',
    'origin-6',
    'tv-1979',
    'movie-1',
    'movie-2',
    'movie-3',
    '08th-ms-team',
    '0080',
    '0083',
    'zeta',
    'zz',
    'char-counterattack',
    'unicorn',
    'narrative',
    'hathaway',
    'hathaway-2',
  ],
  recommendedLabel: '初見が挫折しない順',
  recommendedDescription:
    '宇宙世紀を初めて観る人向けの順です。43話のTV版ではなく劇場版3本（合計約5時間）から入り、本筋だけを追います。外伝OVAは本筋を観たあとで、興味が続いていれば足せば十分です。',
  recommendedOrder: [
    { slug: 'movie-1', reason: 'TV版43話の代わりにここから。3本で一年戦争が完結する' },
    { slug: 'movie-2' },
    { slug: 'movie-3', reason: 'ここで1stが完結する。この3本だけで一区切りつく' },
    { slug: 'zeta', reason: '7年後の話。ここから急に重くなるが、逆襲のシャアに必要な前提がそろう' },
    {
      slug: 'zz',
      reason: 'Zの直接の続き。序盤の明るい作風が合わなければ飛ばしても、逆襲のシャアは追える',
    },
    { slug: 'char-counterattack', reason: 'アムロとシャアの決着。ここが宇宙世紀のひとつの終着点' },
  ],
  caveats: [
    'ガンダムシリーズ全体には順番がありません。SEED、00、鉄血のオルフェンズ、水星の魔女、Gガンダム、W、Xなどは宇宙世紀とは別の世界で、互いに繋がっていません。どれから観ても構いませんし、宇宙世紀を観ていなくても支障はありません。',
    'TV版『機動戦士ガンダム』（43話）と劇場版3部作は、同じ話の別バージョンです。両方観る必要はありません。劇場版は3本で約5時間にまとまっている代わりに、TV版にあった細かい描写が省かれています。また劇場版IIIの終盤は新作カットに差し替えられており、結末の見え方が変わります。',
    '外伝OVA（0080・0083・第08MS小隊）は、本編より後に作られた一年戦争前後の話です。年代順に観ようとすると制作年が20年近く前後するため、映像や作風の落差が大きくなります。本編を先に通してから足すほうが違和感が少なくなります。',
    '『機動戦士ガンダム THE ORIGIN』は全6章で、年代順では最初に来ます。ただし1stガンダムの登場人物を知っている前提で作られているため、年代順を厳密に守って最初に観ると、誰の話なのか分からないまま進むことになります。なお2019年放送の『THE ORIGIN 前夜 赤い彗星』は、この6章を再編集したTV版で、内容は重複します。',
    '『機動戦士Gundam GQuuuuuuX（ジークアクス）』（2025年）は宇宙世紀を舞台にしていますが、一年戦争の結末が史実と異なる分岐世界の話です。ここまでの年表には接続しないため、上の順番には含めていません。',
    '『閃光のハサウェイ』は3部作の予定で、第2部『キルケーの魔女』が2026年1月30日に公開されました。完結編はまだ公開されていません。',
    '『Zガンダム』には劇場版3部作（2005〜2006年）もありますが、結末がTV版と異なります。TV版と劇場版のどちらを正史とするかは公式にも整理されていないため、ここではTV版を基準にしています。',
  ],
  sources: [
    {
      label: 'GUNDAM.INFO（バンダイナムコフィルムワークス公式ポータル）',
      url: 'https://www.gundam.info/',
    },
    {
      label: '映画『機動戦士ガンダム 閃光のハサウェイ』公式サイト',
      url: 'https://gundam-hathaway.net/',
    },
    {
      label: '機動戦士Gundam GQuuuuuuX 公式サイト',
      url: 'https://www.gquuuuuux.net/',
    },
  ],
};
