import type { Series } from '@/lib/types';

/**
 * 時系列順は Disney+ / Marvel.com の公式タイムライン（劇場長編のみ抽出）に従う。
 * 公式順は厳密な設定年代の昇順ではない箇所があり、そこは note に明記した。
 */
export const mcu: Series = {
  slug: 'mcu',
  name: 'マーベル・シネマティック・ユニバース',
  tagline: 'MCU 全37作を、公開順・時系列順で',
  description:
    'アイアンマンから始まる MCU の劇場公開長編を、公開順と公式タイムライン順の両方で並べています。公式順は設定年代の厳密な昇順ではなく、いくつか順序が入れ替わる箇所があります。',
  films: [
    { slug: 'iron-man', title: 'アイアンマン', originalTitle: 'Iron Man', year: 2008, setting: '2008年', note: '旧来は2010年とされていたが、2023年の公式書籍で2008年に改められた' },
    { slug: 'incredible-hulk', title: 'インクレディブル・ハルク', originalTitle: 'The Incredible Hulk', year: 2008, setting: '2010年' },
    { slug: 'iron-man-2', title: 'アイアンマン2', originalTitle: 'Iron Man 2', year: 2010, setting: '2010年' },
    { slug: 'thor', title: 'マイティ・ソー', originalTitle: 'Thor', year: 2011, setting: '2010年', note: '『アイアンマン2』『インクレディブル・ハルク』と同時期（Fury’s Big Week）' },
    { slug: 'captain-america-tfa', title: 'キャプテン・アメリカ／ザ・ファースト・アベンジャー', originalTitle: 'Captain America: The First Avenger', year: 2011, setting: '1943〜1945年（枠物語は現代）' },
    { slug: 'avengers', title: 'アベンジャーズ', originalTitle: 'The Avengers', year: 2012, setting: '2012年' },
    { slug: 'iron-man-3', title: 'アイアンマン3', originalTitle: 'Iron Man 3', year: 2013, setting: '2013年（クリスマス）' },
    { slug: 'thor-dark-world', title: 'マイティ・ソー／ダーク・ワールド', originalTitle: 'Thor: The Dark World', year: 2013, setting: '2013年', note: '公式順では『アイアンマン3』より前。ファン間では逆順とする説も根強い' },
    { slug: 'winter-soldier', title: 'キャプテン・アメリカ／ウィンター・ソルジャー', originalTitle: 'Captain America: The Winter Soldier', year: 2014, setting: '2014年' },
    { slug: 'gotg', title: 'ガーディアンズ・オブ・ギャラクシー', originalTitle: 'Guardians of the Galaxy', year: 2014, setting: '2014年（冒頭1988年）' },
    { slug: 'age-of-ultron', title: 'アベンジャーズ／エイジ・オブ・ウルトロン', originalTitle: 'Avengers: Age of Ultron', year: 2015, setting: '2015年' },
    { slug: 'ant-man', title: 'アントマン', originalTitle: 'Ant-Man', year: 2015, setting: '2015年' },
    { slug: 'civil-war', title: 'シビル・ウォー／キャプテン・アメリカ', originalTitle: 'Captain America: Civil War', year: 2016, setting: '2016年' },
    { slug: 'doctor-strange', title: 'ドクター・ストレンジ', originalTitle: 'Doctor Strange', year: 2016, setting: '2016〜2017年' },
    { slug: 'gotg-2', title: 'ガーディアンズ・オブ・ギャラクシー：リミックス', originalTitle: 'Guardians of the Galaxy Vol. 2', year: 2017, setting: '2014年', note: '前作の数か月後。公開は3年後だが作中では直後' },
    { slug: 'homecoming', title: 'スパイダーマン：ホームカミング', originalTitle: 'Spider-Man: Homecoming', year: 2017, setting: '2016年', note: '作中字幕の「8年後」は制作側が誤りと認めている' },
    { slug: 'thor-ragnarok', title: 'マイティ・ソー バトルロイヤル', originalTitle: 'Thor: Ragnarok', year: 2017, setting: '2017年' },
    { slug: 'black-panther', title: 'ブラックパンサー', originalTitle: 'Black Panther', year: 2018, setting: '2016年', note: '2017年説・2018年説もある。公式書籍準拠で2016年' },
    { slug: 'infinity-war', title: 'アベンジャーズ／インフィニティ・ウォー', originalTitle: 'Avengers: Infinity War', year: 2018, setting: '2018年' },
    { slug: 'ant-man-wasp', title: 'アントマン&ワスプ', originalTitle: 'Ant-Man and the Wasp', year: 2018, setting: '2018年', note: '公式順では『インフィニティ・ウォー』より前。ポストクレジットが指パッチンの瞬間' },
    { slug: 'captain-marvel', title: 'キャプテン・マーベル', originalTitle: 'Captain Marvel', year: 2019, setting: '1995年（回想1989年）' },
    { slug: 'endgame', title: 'アベンジャーズ／エンドゲーム', originalTitle: 'Avengers: Endgame', year: 2019, setting: '2018年 →（5年後）2023年' },
    { slug: 'far-from-home', title: 'スパイダーマン：ファー・フロム・ホーム', originalTitle: 'Spider-Man: Far From Home', year: 2019, setting: '2024年' },
    { slug: 'black-widow', title: 'ブラック・ウィドウ', originalTitle: 'Black Widow', year: 2021, setting: '2016年', note: '『シビル・ウォー』直後。ポストクレジットのみ2024年' },
    { slug: 'shang-chi', title: 'シャン・チー／テン・リングスの伝説', originalTitle: 'Shang-Chi and the Legend of the Ten Rings', year: 2021, setting: '2024年' },
    { slug: 'eternals', title: 'エターナルズ', originalTitle: 'Eternals', year: 2021, setting: '2024年（回想は紀元前5000年〜）' },
    { slug: 'no-way-home', title: 'スパイダーマン：ノー・ウェイ・ホーム', originalTitle: 'Spider-Man: No Way Home', year: 2021, setting: '2024年' },
    { slug: 'multiverse-of-madness', title: 'ドクター・ストレンジ／マルチバース・オブ・マッドネス', originalTitle: 'Doctor Strange in the Multiverse of Madness', year: 2022, setting: '2024年（2025年説あり）' },
    { slug: 'love-and-thunder', title: 'ソー：ラブ&サンダー', originalTitle: 'Thor: Love and Thunder', year: 2022, setting: '2025年' },
    { slug: 'wakanda-forever', title: 'ブラックパンサー／ワカンダ・フォーエバー', originalTitle: 'Black Panther: Wakanda Forever', year: 2022, setting: '2025年' },
    { slug: 'quantumania', title: 'アントマン&ワスプ：クアントマニア', originalTitle: 'Ant-Man and the Wasp: Quantumania', year: 2023, setting: '2025年末〜2026年初頭' },
    { slug: 'gotg-3', title: 'ガーディアンズ・オブ・ギャラクシー：VOLUME 3', originalTitle: 'Guardians of the Galaxy Vol. 3', year: 2023, setting: '2026年' },
    { slug: 'the-marvels', title: 'マーベルズ', originalTitle: 'The Marvels', year: 2023, setting: '2025年', note: '設定年（2025年）と公式順（VOLUME 3の後）が食い違う。ここでは公式順を優先' },
    { slug: 'deadpool-wolverine', title: 'デッドプール&ウルヴァリン', originalTitle: 'Deadpool & Wolverine', year: 2024, setting: '2024年', note: '設定年は2024年だが、公式順ではTVA関連の位置に置かれる' },
    { slug: 'brave-new-world', title: 'キャプテン・アメリカ：ブレイブ・ニュー・ワールド', originalTitle: 'Captain America: Brave New World', year: 2025, setting: '2027年' },
    { slug: 'thunderbolts', title: 'サンダーボルツ*', originalTitle: 'Thunderbolts*', year: 2025, setting: '2027年' },
    { slug: 'fantastic-four-first-steps', title: 'ファンタスティック4：ファースト・ステップ', originalTitle: 'The Fantastic Four: First Steps', year: 2025, note: '別宇宙（アース828）が舞台。作中年代は公式に明示されていない' },
  ],
  releaseOrder: [
    'iron-man', 'incredible-hulk', 'iron-man-2', 'thor', 'captain-america-tfa', 'avengers',
    'iron-man-3', 'thor-dark-world', 'winter-soldier', 'gotg', 'age-of-ultron', 'ant-man',
    'civil-war', 'doctor-strange', 'gotg-2', 'homecoming', 'thor-ragnarok', 'black-panther',
    'infinity-war', 'ant-man-wasp', 'captain-marvel', 'endgame', 'far-from-home', 'black-widow',
    'shang-chi', 'eternals', 'no-way-home', 'multiverse-of-madness', 'love-and-thunder',
    'wakanda-forever', 'quantumania', 'gotg-3', 'the-marvels', 'deadpool-wolverine',
    'brave-new-world', 'thunderbolts', 'fantastic-four-first-steps',
  ],
  chronoOrder: [
    'captain-america-tfa', 'captain-marvel', 'iron-man', 'iron-man-2', 'incredible-hulk', 'thor',
    'avengers', 'thor-dark-world', 'iron-man-3', 'winter-soldier', 'gotg', 'gotg-2',
    'age-of-ultron', 'ant-man', 'civil-war', 'black-widow', 'black-panther', 'homecoming',
    'doctor-strange', 'thor-ragnarok', 'ant-man-wasp', 'infinity-war', 'endgame', 'shang-chi',
    'far-from-home', 'eternals', 'no-way-home', 'multiverse-of-madness', 'wakanda-forever',
    'love-and-thunder', 'quantumania', 'gotg-3', 'the-marvels', 'deadpool-wolverine',
    'brave-new-world', 'thunderbolts', 'fantastic-four-first-steps',
  ],
  recommendedOrder: [
    { slug: 'iron-man', reason: 'すべての始まり。ここから観るのが最も自然です' },
    { slug: 'captain-america-tfa', reason: '第二次大戦が舞台。単独で完結しており、ここで観ても混乱しません' },
    { slug: 'avengers', reason: '初めて全員が集まる回。ここまでで一度「MCU とは何か」が分かります' },
    { slug: 'winter-soldier', reason: 'シリーズ全体の流れを変える一本。評価も高く、ここで引き込まれます' },
    { slug: 'gotg', reason: '宇宙側の物語が始まります。地球側と独立して楽しめます' },
    { slug: 'age-of-ultron', reason: '次の大きな山場への布石' },
    { slug: 'civil-war', reason: 'ヒーロー同士の対立。スパイダーマンとブラックパンサーが初登場します' },
    { slug: 'black-panther', reason: 'ワカンダの物語。単独作として完成度が高い' },
    { slug: 'thor-ragnarok', reason: 'ソーの作風が一変します。ここを飛ばすと次で置いていかれます' },
    { slug: 'infinity-war', reason: 'ここまでの積み重ねが集まります' },
    { slug: 'endgame', reason: '第1〜3期の完結。ここで一区切りついてよい' },
    { slug: 'no-way-home', reason: 'ここから先は興味に応じて。まずはこれが分かりやすい入口です' },
  ],
  caveats: [
    'Disney+ の公式タイムライン順は、設定年代の厳密な昇順ではありません。『ダーク・ワールド』→『アイアンマン3』、『アントマン&ワスプ』→『インフィニティ・ウォー』などが入れ替わっています。',
    '『ガーディアンズ・オブ・ギャラクシー：リミックス』は公開こそ3年後ですが、作中では前作の数か月後です。時系列順で観ると連続して並びます。',
    '初見なら公開順をおすすめします。時系列順は、後の作品で明かされる事実を先に知ってしまう箇所があります。',
    'ドラマシリーズ（『ロキ』『ワンダヴィジョン』など）は含めていません。劇場公開の長編のみです。',
  ],
  sources: [
    { label: 'See the Complete MCU Timeline on Disney+ | Marvel', url: 'https://www.marvel.com/articles/movies/mcu-timeline-order-disney-plus' },
    { label: 'Marvel Movies In Order | Screen Rant', url: 'https://screenrant.com/marvel-movies-in-order/' },
  ],
};
