import type { Series } from '@/lib/types';

/**
 * ONE PIECE は「本編の順番」に迷う余地がない。1話から順に観るだけだ。
 * 迷うのは (1) 劇場版をどこに挟むか (2) 1100話超をどこから入るか の2点で、
 * このページはその2つに答えることに絞っている。
 *
 * 本編は TMDb が編ごとにシーズンを切っているので、それをそのまま1エントリにした。
 * 編ごとにポスターと話数が入り、視聴チェックも編単位で追える。
 * year は各編の放送開始年（TMDb のシーズン区分は公式の「編」と完全には一致しない）。
 */
export const onePiece: Series = {
  slug: 'one-piece',
  name: 'ONE PIECE',
  tagline: '本編は迷わない。迷うのは劇場版の位置と、どこから入るか',
  description:
    'ONE PIECE の本編は1話から順に観るだけで、順番に迷う余地はありません。問題になるのは、16本ある劇場版をどこに挟むのか、そして1100話を超えた本編にどこから入るのかです。劇場版の多くは本編と地続きではありませんが、尾田栄一郎が総合プロデューサーとして関わった作品には、本編側に連動するエピソードが用意されていて、それが挟む位置の根拠になります。2027年2月には東の海編を再アニメ化した『THE ONE PIECE』が始まるため、「1999年版とリメイク版のどちらから入るか」という問いも新しく生まれます。',
  films: [
    // ── 本編（TMDb #37854 のシーズン＝編） ──
    {
      slug: 'east-blue',
      title: '東の海編',
      originalTitle: '東の海編',
      year: 1999,
      kind: 'tv',
      episodes: 61,
      tmdbId: 37854,
      season: 1,
      note: 'ルフィが仲間を集めながらグランドラインを目指す。ここだけで一区切りつくので、合わないと感じたら先へ進む必要はない',
    },
    {
      slug: 'grand-line',
      title: 'グランドライン突入編',
      originalTitle: 'グランドライン突入編',
      year: 2001,
      kind: 'tv',
      episodes: 16,
      tmdbId: 37854,
      season: 2,
    },
    {
      slug: 'drum',
      title: 'チョッパー登場・冬島編',
      originalTitle: 'チョッパー登場・冬島編',
      year: 2001,
      kind: 'tv',
      episodes: 14,
      tmdbId: 37854,
      season: 3,
    },
    {
      slug: 'alabasta',
      title: 'アラバスタ編',
      originalTitle: 'アラバスタ編',
      year: 2001,
      kind: 'tv',
      episodes: 39,
      tmdbId: 37854,
      season: 4,
    },
    {
      slug: 'tv-original',
      title: 'TVオリジナル編',
      originalTitle: 'TVオリジナル',
      year: 2002,
      kind: 'tv',
      episodes: 13,
      tmdbId: 37854,
      season: 5,
      note: 'TMDb が「TVオリジナル」として区切っている、原作にない編。飛ばしても本編の筋は繋がる',
    },
    {
      slug: 'skypiea',
      title: '空島編',
      originalTitle: '空島編',
      year: 2003,
      kind: 'tv',
      episodes: 52,
      tmdbId: 37854,
      season: 6,
    },
    {
      slug: 'g8-foxy',
      title: '脱出!海軍要塞&フォクシー海賊団編',
      originalTitle: '脱出!海軍要塞&フォクシー海賊団編',
      year: 2004,
      kind: 'tv',
      episodes: 33,
      tmdbId: 37854,
      season: 7,
      note: 'アニメオリジナルの回と原作の回が混在する編',
    },
    {
      slug: 'water-seven',
      title: 'ウォーターセブン編',
      originalTitle: 'ウォーターセブン編',
      year: 2005,
      kind: 'tv',
      episodes: 35,
      tmdbId: 37854,
      season: 8,
    },
    {
      slug: 'enies-lobby',
      title: 'エニエス・ロビー編',
      originalTitle: 'エニエス・ロビー編',
      year: 2006,
      kind: 'tv',
      episodes: 73,
      tmdbId: 37854,
      season: 9,
    },
    {
      slug: 'thriller-bark',
      title: 'スリラーバーク編',
      originalTitle: 'スリラーバーク編',
      year: 2008,
      kind: 'tv',
      episodes: 45,
      tmdbId: 37854,
      season: 10,
    },
    {
      slug: 'sabaody',
      title: 'シャボンディ諸島編',
      originalTitle: 'シャボンディ諸島編',
      year: 2009,
      kind: 'tv',
      episodes: 26,
      tmdbId: 37854,
      season: 11,
    },
    {
      slug: 'amazon-lily',
      title: '女ヶ島編',
      originalTitle: '女ヶ島編',
      year: 2009,
      kind: 'tv',
      episodes: 14,
      tmdbId: 37854,
      season: 12,
    },
    {
      slug: 'impel-down',
      title: 'インペルダウン編',
      originalTitle: 'インペルダウン編',
      year: 2010,
      kind: 'tv',
      episodes: 101,
      tmdbId: 37854,
      season: 13,
    },
    {
      slug: 'marineford',
      title: 'マリンフォード編',
      originalTitle: 'マリンフォード編',
      year: 2011,
      kind: 'tv',
      episodes: 58,
      tmdbId: 37854,
      season: 14,
      note: 'いわゆる頂上戦争。ここで物語が大きく折り返す',
    },
    {
      slug: 'fishman-island',
      title: '魚人島編',
      originalTitle: '魚人島編',
      year: 2012,
      kind: 'tv',
      episodes: 62,
      tmdbId: 37854,
      season: 15,
    },
    {
      slug: 'punk-hazard',
      title: 'パンクハザード編',
      originalTitle: 'パンクハザード編',
      year: 2013,
      kind: 'tv',
      episodes: 50,
      tmdbId: 37854,
      season: 16,
    },
    {
      slug: 'dressrosa',
      title: 'ドレスローザ編',
      originalTitle: 'ドレスローザ編',
      year: 2014,
      kind: 'tv',
      episodes: 56,
      tmdbId: 37854,
      season: 17,
    },
    {
      slug: 'zou',
      title: 'ゾウ編',
      originalTitle: 'ゾウ編',
      year: 2016,
      kind: 'tv',
      episodes: 55,
      tmdbId: 37854,
      season: 18,
    },
    {
      slug: 'whole-cake',
      title: 'ホールケーキアイランド編',
      originalTitle: 'ホールケーキアイランド編',
      year: 2017,
      kind: 'tv',
      episodes: 74,
      tmdbId: 37854,
      season: 19,
    },
    {
      slug: 'reverie',
      title: 'レヴェリー編',
      originalTitle: 'レヴェリー編',
      year: 2019,
      kind: 'tv',
      episodes: 14,
      tmdbId: 37854,
      season: 20,
    },
    {
      slug: 'wano',
      title: 'ワノ国編',
      originalTitle: 'ワノ国編',
      year: 2019,
      kind: 'tv',
      episodes: 197,
      tmdbId: 37854,
      season: 21,
      note: '単独で197話ある、シリーズ最長の編',
    },
    {
      slug: 'egghead',
      title: 'エッグヘッド編',
      originalTitle: 'エッグヘッド編',
      year: 2024,
      kind: 'tv',
      episodes: 67,
      tmdbId: 37854,
      season: 22,
    },
    {
      slug: 'elbaf',
      title: 'エルバフ編',
      originalTitle: 'エルバフ編',
      year: 2026,
      kind: 'tv',
      episodes: 26,
      tmdbId: 37854,
      season: 23,
      note: '2026年4月5日放送開始。放送中のため話数は今後増える',
    },

    // ── 劇場版 ──
    {
      slug: 'movie-1',
      title: 'ONE PIECE',
      originalTitle: 'ONE PIECE',
      year: 2000,
      note: '初の劇場版。約50分の短編',
    },
    {
      slug: 'movie-2',
      title: 'ONE PIECE ねじまき島の冒険',
      originalTitle: 'ONE PIECE ねじまき島の冒険',
      year: 2001,
    },
    {
      slug: 'movie-3',
      title: 'ONE PIECE 珍獣島のチョッパー王国',
      originalTitle: 'ONE PIECE 珍獣島のチョッパー王国',
      year: 2002,
    },
    {
      slug: 'movie-4',
      title: 'ONE PIECE THE MOVIE デッドエンドの冒険',
      originalTitle: 'ONE PIECE THE MOVIE デッドエンドの冒険',
      year: 2003,
    },
    {
      slug: 'movie-5',
      title: 'ONE PIECE 呪われた聖剣',
      originalTitle: 'ONE PIECE 呪われた聖剣',
      year: 2004,
    },
    {
      slug: 'movie-6',
      title: 'ONE PIECE THE MOVIE オマツリ男爵と秘密の島',
      originalTitle: 'ONE PIECE THE MOVIE オマツリ男爵と秘密の島',
      year: 2005,
      note: '細田守が監督した異色作。作風が他作と大きく異なることで知られる',
    },
    {
      slug: 'movie-7',
      title: 'ONE PIECE THE MOVIE カラクリ城のメカ巨兵',
      originalTitle: 'ONE PIECE THE MOVIE カラクリ城のメカ巨兵',
      year: 2006,
    },
    {
      slug: 'episode-of-alabasta',
      title: 'ONE PIECE エピソードオブアラバスタ 砂漠の王女と海賊たち',
      originalTitle: 'ONE PIECE エピソードオブアラバスタ 砂漠の王女と海賊たち',
      year: 2007,
      note: 'アラバスタ編の総集編。本編を観ているなら内容は重複する',
    },
    {
      slug: 'episode-of-chopper',
      title: 'ONE PIECE THE MOVIE エピソードオブチョッパープラス 冬に咲く、奇跡の桜',
      originalTitle: 'ONE PIECE THE MOVIE エピソードオブチョッパー＋（プラス） 冬に咲く、奇跡の桜',
      year: 2008,
      note: '冬島編（チョッパー登場編）を作り直したもの。設定に変更があり、本編とは別バージョンにあたる',
    },
    {
      slug: 'strong-world',
      title: 'ONE PIECE FILM STRONG WORLD',
      originalTitle: 'ONE PIECE FILM STRONG WORLD',
      year: 2009,
      note: '尾田栄一郎が総合プロデューサーとして参加した最初の作品。本編426〜429話が連動エピソードにあたる',
    },
    {
      slug: 'movie-3d',
      title: 'ONE PIECE 3D 麦わらチェイス',
      originalTitle: 'ONE PIECE 3D 麦わらチェイス',
      year: 2011,
      note: '約30分の3D短編。本編との接続はとくにない',
    },
    {
      slug: 'film-z',
      title: 'ONE PIECE FILM Z',
      originalTitle: 'ONE PIECE FILM Z',
      year: 2012,
      note: '尾田栄一郎が総合プロデューサー。本編575〜578話が連動エピソードにあたる',
    },
    {
      slug: 'film-gold',
      title: 'ONE PIECE FILM GOLD',
      originalTitle: 'ONE PIECE FILM GOLD',
      year: 2016,
      note: '尾田栄一郎が総合プロデューサー。本編747〜750話が連動エピソードにあたる',
    },
    {
      slug: 'stampede',
      title: 'ONE PIECE STAMPEDE',
      originalTitle: 'ONE PIECE STAMPEDE',
      year: 2019,
      note: 'アニメ20周年記念作。本編895〜896話が連動エピソードにあたる',
    },
    {
      slug: 'film-red',
      title: 'ONE PIECE FILM RED',
      originalTitle: 'ONE PIECE FILM RED',
      year: 2022,
      note: '尾田栄一郎が総合プロデューサー。本編1029〜1030話が連動エピソードにあたる',
    },
    {
      slug: 'god-valley',
      title: 'ONE PIECE FILM GOD VALLEY',
      originalTitle: 'ONE PIECE FILM GOD VALLEY',
      year: 2027,
      note: '2027年夏公開予定。公開前のため、本編のどこに接続するかは未確定',
    },

    // ── 再アニメ化 ──
    {
      slug: 'the-one-piece',
      title: 'THE ONE PIECE',
      originalTitle: 'THE ONE PIECE',
      year: 2027,
      kind: 'tv',
      episodes: 7,
      tmdbId: 241709,
      note: '2027年2月Netflix世界独占配信。WIT STUDIO制作で、原作1話から東の海編を作り直す。シーズン1は全7話で、ルフィがバラティエでサンジと出会うところまで',
    },
  ],
  releaseOrder: [
    'east-blue',
    'movie-1',
    'grand-line',
    'movie-2',
    'drum',
    'alabasta',
    'tv-original',
    'movie-3',
    'skypiea',
    'movie-4',
    'g8-foxy',
    'movie-5',
    'water-seven',
    'movie-6',
    'enies-lobby',
    'movie-7',
    'episode-of-alabasta',
    'thriller-bark',
    'episode-of-chopper',
    'sabaody',
    'amazon-lily',
    'strong-world',
    'impel-down',
    'marineford',
    'movie-3d',
    'fishman-island',
    'film-z',
    'punk-hazard',
    'dressrosa',
    'zou',
    'film-gold',
    'whole-cake',
    'reverie',
    'wano',
    'stampede',
    'film-red',
    'egghead',
    'elbaf',
    'the-one-piece',
    'god-valley',
  ],
  chronoOrder: [
    'east-blue',
    'the-one-piece',
    'movie-1',
    'grand-line',
    'movie-2',
    'drum',
    'episode-of-chopper',
    'movie-3',
    'alabasta',
    'episode-of-alabasta',
    'movie-4',
    'tv-original',
    'movie-5',
    'skypiea',
    'movie-6',
    'g8-foxy',
    'movie-7',
    'water-seven',
    'enies-lobby',
    'thriller-bark',
    'strong-world',
    'sabaody',
    'amazon-lily',
    'impel-down',
    'marineford',
    'movie-3d',
    'fishman-island',
    'film-z',
    'punk-hazard',
    'dressrosa',
    'film-gold',
    'zou',
    'whole-cake',
    'reverie',
    'stampede',
    'wano',
    'film-red',
    'egghead',
    'elbaf',
    'god-valley',
  ],
  recommendedLabel: '劇場版を挟まず本編だけ観る順',
  recommendedDescription:
    '劇場版をすべて外し、本編だけを順に観る順です。劇場版は本編と地続きではないため、これだけで物語は問題なく追えます。まず本編を進めて、気に入ったら劇場版を足すのが迷いません。',
  recommendedOrder: [
    { slug: 'east-blue', reason: 'ここから始まる。61話で一区切りつくので、合うかどうかはここで判断できる' },
    { slug: 'grand-line' },
    { slug: 'drum' },
    { slug: 'alabasta', reason: '最初の大きな山場。ここまで来れば作品の型がつかめる' },
    { slug: 'tv-original', reason: '原作にないアニメオリジナル編。急ぐなら飛ばしてよい' },
    { slug: 'skypiea' },
    { slug: 'g8-foxy' },
    { slug: 'water-seven' },
    { slug: 'enies-lobby' },
    { slug: 'thriller-bark' },
    { slug: 'sabaody' },
    { slug: 'amazon-lily' },
    { slug: 'impel-down' },
    { slug: 'marineford', reason: '頂上戦争。ここで物語が大きく折り返す' },
    { slug: 'fishman-island' },
    { slug: 'punk-hazard' },
    { slug: 'dressrosa' },
    { slug: 'zou' },
    { slug: 'whole-cake' },
    { slug: 'reverie' },
    { slug: 'wano', reason: '197話ある最長の編。ここが最大の関門になる' },
    { slug: 'egghead' },
    { slug: 'elbaf', reason: '2026年4月から放送中。ここで現在に追いつく' },
  ],
  caveats: [
    '本編の順番に迷う余地はありません。1話から順に観るだけです。このページで整理しているのは「劇場版をどこに挟むか」と「どこから入るか」の2点だけです。',
    '劇場版は基本的に本編と地続きではありません。尾田栄一郎が総合プロデューサーとして関わっているのは FILM シリーズ以降で、それ以前の作品はサイドストーリーの位置づけです。本編を追ううえで劇場版を観る必要はなく、観なくても話は繋がります。',
    'ただし尾田栄一郎が関わった作品には、本編側に連動するエピソードが用意されています。STRONG WORLD は426〜429話、FILM Z は575〜578話、FILM GOLD は747〜750話、STAMPEDE は895〜896話、FILM RED は1029〜1030話です。「本編のどのあたりで観るか」を制作側が示しているのはこの区間なので、時系列順ではそこに置いています。',
    '『エピソードオブアラバスタ』はアラバスタ編の総集編、『エピソードオブチョッパー』は冬島編を作り直したものです。どちらも本編を観ていれば内容が重複します。とくに『エピソードオブチョッパー』は設定に変更があり、本編とは別バージョンにあたります。',
    '2027年2月から、原作1話を作り直す『THE ONE PIECE』がNetflixで始まります。1999年版の東の海編と同じ範囲を描くので、両方を観る必要はありません。ただしシーズン1は全7話で、ルフィがバラティエでサンジと出会うところまでしか進みません。続きを追うなら結局1999年版に戻ることになるため、先の展開まで一気に観たい場合は最初から1999年版で始めるほうが途切れません。',
    'Netflixの実写ドラマ版（2023年〜）も同じ東の海編から始まりますが、媒体の違う翻案なので上の順番には含めていません。',
    '本編は1100話を超えており、話数の多さそのものが最大の壁です。全編を追う前提で構えるより、まず東の海編の61話だけを観て、合うかどうかを判断するのが現実的です。',
    'ここで使っている編の区切りは TMDb のシーズン区分に合わせています。公式が使う「編」の呼び方や範囲とは、境目が一部ずれることがあります。',
  ],
  sources: [
    {
      label: 'ONE PIECE.com（公式ポータル）',
      url: 'https://one-piece.com/',
    },
    {
      label: 'Netflix「THE ONE PIECE」2027年2月世界独占配信決定（公式発表）',
      url: 'https://about.netflix.com/ja/news/the-one-piece-coming-february-2027',
    },
    {
      label: 'ONE PIECE (アニメ) - Wikipedia（劇場版の連動エピソード）',
      url: 'https://ja.wikipedia.org/wiki/ONE_PIECE_(%E3%82%A2%E3%83%8B%E3%83%A1)',
    },
  ],
};
